Traceback (most recent call last):
  File "/Users/adamaiken/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/adamaiken/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/adamaiken/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/adamaiken/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/adamaiken/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/adamaiken/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/adamaiken/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/adamaiken/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plt.figure(figsize=(10, 6))

stocks.aapl_ret = np.log(stocks.aapl_o / stocks.aapl_o.shift(1))  
stocks.msft_ret = np.log(stocks.msft_o / stocks.msft_o.shift(1))  

plt.scatter(stocks.aapl_ret, stocks.msft_ret, marker = 'o')
plt.xlabel('aapl')
plt.ylabel('msft')
plt.title('Apple vs. MSFT');

print('The correlation between AAPL and MSFT is ' + str(aapl_retstocks.aapl_ret.corr(stocks.msft_ret).round(3)))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/sm/f4lq92s11392x68kwf0scq3w0000gn/T/ipykernel_12615/3662927572.py[0m in [0;36m<module>[0;34m[0m
[1;32m      9[0m [0mplt[0m[0;34m.[0m[0mtitle[0m[0;34m([0m[0;34m'Apple vs. MSFT'[0m[0;34m)[0m[0;34m;[0m[0;34m[0m[0;34m[0m[0m
[1;32m     10[0m [0;34m[0m[0m
[0;32m---> 11[0;31m [0mprint[0m[0;34m([0m[0;34m'The correlation between AAPL and MSFT is '[0m [0;34m+[0m [0mstr[0m[0;34m([0m[0maapl_retstocks[0m[0;34m.[0m[0maapl_ret[0m[0;34m.[0m[0mcorr[0m[0;34m([0m[0mstocks[0m[0;34m.[0m[0mmsft_ret[0m[0;34m)[0m[0;34m.[0m[0mround[0m[0;34m([0m[0;36m3[0m[0;34m)[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'aapl_retstocks' is not defined
NameError: name 'aapl_retstocks' is not defined

